### PR TITLE
fill disregards strokestyle

### PR DESCRIPTION
**Pull request by CodeGod911**
sry to bother again but i didnt notice the whole afternoon :)
grafik

### CODE REVIEW

**Comment by MarvinKlein1508** [comment]
Can you clarify how I can reproduce? For me it works fine.

**Comment by CodeGod911** [comment]
its just perfect dots so stay absolutely still and click then draw around. but i noticed something else ill look into it closer

**Comment by CodeGod911** [comment]
i dont quite like this rectangle dot but i think its a limitation of the canvas in the BG Demo
grafik
Much better in Options Demo
grafik

**Comment by CodeGod911** [comment]
There is actually a huge issue not clearing before redrawing because the last points differ in calculation on slower devices this results in very bad artifacts
grafik

**Comment by CodeGod911** [comment]
this fix looks much better at the cost of being 1 frame behind while drawing which i think is acceptable
grafik

**Review by MarvinKlein1508 — APPROVED** [review]
LGTM

**Pull request merged**
